[phases.setup]
cmds = [
  "apt-get update && apt-get install -y python3.12 python3.12-venv python3.12-dev python3-pip build-essential cmake libjpeg-dev zlib1g-dev"
]

[phases.install]
cmds = [
  "python3.12 -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"
]

[phases.start]
cmd = "python3.12 app.py"
